version: '3.7'
services:
  # MSSQL Database
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: my_sqlserver
    environment:
      SA_PASSWORD: z+nr&Ij7CS3ccv2   
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - my_network

  # Redis Cache
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - my_network
    volumes:
      - ./redis.conf:/etc/redis/redis.conf

  # RabbitMQ
  messaging:
    image: "rabbitmq:3-management-alpine"
    container_name: my_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    networks:
      - my_network

networks:
  my_network:
